const {
  REACT_APP_REC_COGNITO_CLIENT_ID,
  REACT_APP_REC_COGNITO_SECRET,
  REACT_APP_REC_COGNITO_DOMAIN,
  REACT_APP_REC_COGNITO_REGION,
} = process.env;

const config = {
  clientId: REACT_APP_REC_COGNITO_CLIENT_ID,
  clientSecret: REACT_APP_REC_COGNITO_SECRET,
  domain: REACT_APP_REC_COGNITO_DOMAIN,
  region: REACT_APP_REC_COGNITO_REGION,
};

export default config;
